### ISSUE TITLE
Separator in modified multi-value tags

### ISSUE THREAD

**Issue by username116** [ghDaYuYu/foo_discogs#79] opened 2022-09-24 17:14 UTC
Hello,

I have a problem with Style tag (maybe Genre too) that have multiple values.
If I manually change a value before saving, I think the separator ";" is not interpreted as a separator. 
For example here in the Style tag, I replaced a value "Classical" by "Modern Classical". I then show the result in Mp3Tag, and finally how I think it should be.
Tested with foo_discogger 1.0.14 and foobar 2.0 beta 10 x86
![Capture d'écran 76 foobar2000](https://user-images.githubusercontent.com/108369600/192109921-5ddf1e41-d95d-445c-ab43-d5e9b4a6d3d3.png)
![Capture d'écran 77 foobar2000](https://user-images.githubusercontent.com/108369600/192109931-5c208422-0f2d-4696-9ae0-5c81ba2d0126.png)
![Capture d'écran 80 Mp3tag modif](https://user-images.githubusercontent.com/108369600/192109942-1e8609b5-fb98-4533-be8e-79c2dd21228c.png)
![Capture d'écran 81 Mp3tag modif](https://user-images.githubusercontent.com/108369600/192109948-0d890878-2c4f-4934-b444-a80441b379a8.png)

I think I saw a spelling mistake here. Shouldn't it be "Apply" instead of "Appy"?
![Capture d'écran 79 foobar2000 2](https://user-images.githubusercontent.com/108369600/192110420-5e859a04-cf90-46bc-ad4d-7ba5679a20b2.png)

**Comment by ghuDaYuYu** [comment] 2022-09-25 11:14
Hello, thanks for your feedback.

Yes, that 'Appy' should be 'Apply', also edited multi-values need to be trimmed,

Those two fixes will be included in 1.0.14.1.

About the current issue, unfortunately I can´t reproduce it here,
just getting the results as you mentioned they should be (STYLE, DISCOGS_STYLE and GENRE).

Have you tried to edit DISCOGS_STYLE from the the fb2k properties panel, does it make any difference?

**Comment by ghuDaYuYu** [comment] 2022-09-25 11:29
Oh, I see... the bug might be in the Edit (in-place) in the preview panel, not the detailed preview.
That Appy🍎 mislead my tests... I´ll try to fix it as soon as possible,
thanks!

**Comment by ghuDaYuYu** [comment] 2022-09-25 17:57
It´s a great bug report!
I should apologize I dont use the translator and grammar checker as often as I should!
... and of course the bug being reported is quite embarrasing indeed! 

Below you can find 1.0.14.1 prelease, in case you´d like to give it a try and confirm it's working,
maybe new bugs have been introduced...

Both preview and detailed preview were buggy, so there is an attempt to fix that, trimming values and the spelling.

For this pre-release, I had to define a reduced set of multivalue fields, though:

"ARTIST", "ALBUM ARTIST", "PRODUCER", "COMPOSER", "PERFORMER", "GENRE", "STYLE", "DISCOGS_GENRE", "DISCOGS_STYLE"

It will be great if you'd like to test this fix, but no obligation ☺️

Thanks again for your feedback, I am glad having a multivalue related topic being reported.

[zipped 1.0.14.1 preview.zip](https://github.com/ghDaYuYu/foo_discogs/files/9641432/zipped.1.0.14.1.preview.zip)

**Comment by ghuDaYuYu** [comment] 2022-09-26 00:25
Je comprends et parle un peu, mais je ne l'écris pas, en fait, je ne sais pas comment écrire dans une langue, je pense. J'ai adoré l'attitude de Rita quand nous étions plus jeunes, et je suis toujours un fan.
Ma langue maternelle est l'espagnol... il peut être plus approprié comme documentation continuer avec l'anglais mais vous pouvez écrire dans la langue que vous souhaitez, bien sûr. Il n'y a pas beaucoup de gens ici et je ne pense pas que ce soit une poblema.

Creo que he resuelto algunos fallos...

I can not replicate those last two errors, fatal error and crash on this new 14.2

Fixing last preview:

- Edits only applied to the first track.
- Crash increasing multivalue set size.

Give it a try, if you like... no hurry,
I might post a few more pre-releases here as I find time to continue testing.

Je vous remercie beaucoup pour votre aide!

[zipped 1.0.14.2 preview](https://github.com/ghDaYuYu/foo_discogs/files/9642097/zipped.1.0.14.2.preview.zip)

**Comment by ghuDaYuYu** [comment] 2022-09-28 00:02
Thanks for the update 👍 


Yes, the _multi-value fields_ value was applying its default value instead of the user defined, etc

This new release, should fix  the custom multi-value field, the tag mapping import/export dialog has also been patched, thanks for noticing.

The component now logs tag write operations to the console:

![log](https://user-images.githubusercontent.com/62167612/192647401-3bedb1d7-508b-4742-93a7-069867424de5.png)

Just bare bone, but should provide some clues. 

Also, to help troubleshooting, the preview panel stays open after clicking Write tags

![dsk](https://user-images.githubusercontent.com/62167612/192651536-672dc8b2-4a3b-4956-800e-7ea9bead5142.png)


... and a new option to copy values to the lead-in tab in the detailed preview.

![copy to lead-in](https://user-images.githubusercontent.com/62167612/192651694-b289a13d-c7e9-4a22-bf77-cec3ae1d0f2b.png)


That´s it for now... I am also using Mp3Tag as in your recommendation, thanks! 


[zipped 1.0.14.2 preview.zip](https://github.com/ghDaYuYu/foo_discogs/files/9660187/zipped.1.0.14.2.preview.zip)

**Comment by ghuDaYuYu** [comment] 2022-09-28 14:20
Hi, been reading, with a bit more time, from the beginning,
checking how this issue is getting resolved.

- When I edit the tags of one file, it seems to be fine

This bug was found and fixed, it did affect the first item in a selection

- When I edit the tags, it crashes

It can be seen in your screen capture that pressing enter in DISCOGS_STYLE triggers an edit of the field below, DISCOGS_RELEASE_ID. That crashed as that field is protected. Bug was introduced while updating UI to dark mode. Should be fixed now.

- If I remap the tags, the values are not separated
- Going back to the default tags after remaping
- Confusion between the words tag/value

That is still unresolved, it might be worth to comment that currently, when the Tag mapping is committed (by applying changes in the tag mapping panel) all manual edits are invalidated and replaced by the generated values. That is the reason for the foot note in the detailed preview panel 'Values subjected to tag remapping'.
Not sure if that will change soon. I would like to implement a right-click option to write individual tags in the normal preview panel first.
 
I wouldn´t bother much about confusion with the words just now, sometimes a bit of confusion or misunderstanding can´t be that bad.
- DISCOGS_ARTIST_ID is regularly multi-value

That would depend, in my opinion, if that´s helpful somehow (needed by an app, script, layout...).
Related to this, there might be a bug showing in my last screenshot log, as it seams it shows a non-multivalue tag being saved as a being one.

**Comment by ghuDaYuYu** [comment] 2022-09-29 21:05
Trim as remove any leading or trailing spaces, haha

Yes, you are right. Once you save your edits, they become the original.
Sadly, the Write tags button will close the dialog as before in the next release.

Maybe the issue can remain open until v1.0.15 release date...

... et merci beaucoup pour votre aide, nous avons trouvé de nombreux bugs qui sont passés inaperçus, jusqu'à la prochaine fois!

**Comment by ghuDaYuYu** [comment] 2022-09-30 16:14
Changes:

- Option to auto-update config fields on Discogs multivalue tag detection.

![tagging_preferences](https://user-images.githubusercontent.com/62167612/193311589-ef7b7aad-409a-47a6-92a0-392e80f48b0e.png)


Fixes:
- Crash saving Multi-value fields (preference panel)
- Edited multi-value saved as single value (Discogs multi-value fields holding just one value treated as single value fields).

Todo:
- Split value context menu option

[Uploading zipped 1.0.14.3.zip…]()

**Comment by ghuDaYuYu** [comment] 2022-09-30 23:28
geesh! my bad...
I had to undo a very (VERY) old fix to continue with these multi-value fix series,
Unfortunately we are downgrading next release to alpha now, total uncertainty!

I fixed the crash affecting the Origamibiro release, thanks for the crash report.

... and here is 1.014.4 alpha, quite miraculous if it´s not crashing now and them, sorry.

[zipp 1.0.14.4 alpha](https://github.com/ghDaYuYu/foo_discogs/files/9688079/zipp.1.0.14.4.alpha.zip)

I will refrain from posting 14.5 until I find time for a complete testing.
but feel free (if not exhausted yet) to run if you are curious about were it crashes next! 💯

**Comment by ghuDaYuYu** [comment] 2022-10-02 06:04
Fixes:

- Regressions caused by 1.0.14.3 update.
- Auto-append duplicated fields
- Detailed preview multi-values
- Crash overwriting .tm files
- Crash loading album artwork preview

Other fixes/revisions:
- Discard numeric suffixes 

[zipped 1.0.14.5 prerelease](https://github.com/ghDaYuYu/foo_discogs/files/9691864/zipped.1.0.15.5.prerelease.zip)

**Comment by username116** [comment] 2022-10-02 14:53
I'm trying it with remapped tags and modified values. It only works if the new box "Auto-update fields while saving Discogs tags" is checked. I don't know if this is normal.
I try to do this:

![Capture d'écran 104 foobar2000](https://user-images.githubusercontent.com/108369600/193460166-a3b89483-d1aa-4ad6-8735-17ece530421c.png)

With these settings:

![Capture d'écran 102 foobar2000](https://user-images.githubusercontent.com/108369600/193460169-d77d4cdb-f450-48d7-b1b6-0022ecdbed15.png)

After clicking on "write tags", the tags DISCOGS_GENRE and DISCOGS_STYLE are empty.
The console [says that](https://gist.github.com/username116/2d5617e1de754a6b65fbb8c65a4a3d8b).
If I check the box "Auto-update fields..." and try again, it works.

**Comment by ghuDaYuYu** [comment] 2022-10-02 20:11
Thanks for the test case, brief and to the point...

These are my results after 14.6 fixes, with auto-update fields turned off:

log saving unaltered results:
[log_write_res.txt](https://github.com/ghDaYuYu/foo_discogs/files/9693355/log_write_res.txt)
log updating:
[log_update.txt](https://github.com/ghDaYuYu/foo_discogs/files/9693358/log_update.txt)
log writing & updating in one go (user case in your post)
[log_write_res_and_edited.txt](https://github.com/ghDaYuYu/foo_discogs/files/9693361/log_write_res_and_edited.txt)

Still need to test if editing from the detailed preview is bug free.

> I'm trying it with remapped tags and modified values. It only works if the new box "Auto-update fields while saving Discogs tags" is checked. I don't know if this is normal.

No, there was a bug, forgot to disable it while testing... should be fixed now.
Looking now at the config panel, it might be also helpful to add an option to disable all multi-value fields.

It seams that v1.0.14.3 was not as broken as I initially though, maybe problems will arise tagging specific releases.

Here is a brief 14.6 change log:

Fixes:
- multi-value field preference algo bug

Other fixes:
- import/export filename codepage
- text copied to clipboard not pasting to notepad 11


[zip 1.0.14.6 prerelease](https://github.com/ghDaYuYu/foo_discogs/files/9693395/zip.1.0.14.6.prerelease.zip)

**Comment by username116** [comment] 2022-10-03 18:17
I tried the 1.0.14.6 prerelease with the same albums, with edited values, with and without the checkbox.
I also tagged some other albums.
It worked, no bugs to report.
The Auto-update function which adds itself a multi-value tag in the setting worked too.

Thanks for all the improvements.

**Comment by ghuDaYuYu** [comment] 2022-10-10 15:44
You are welcome!
Closing with [v1.0.14.7](https://github.com/ghDaYuYu/foo_discogs/releases/tag/v1.0.14.7)

**Closed by ghuDaYuYu** 2022-10-10 15:44 UTC
