### ISSUE TITLE
Checking show id makes the releases disappear

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#16] opened 2021-03-26 21:54 UTC
See gif.

![XSGLaGdYaV](https://user-images.githubusercontent.com/14054664/112696492-d3c6a800-8e7d-11eb-9d0a-ef1f64696214.gif)

**Comment by ghDaYuYu** [comment] 2021-03-27 01:39
Run a basic test for this and it did not produce an empty list. 
Are sources tagged (either with artist, artist Id, master Id or release Id) or untagged?
Just guessing here... did you select other artists (allowing them to complete loading) before going back to T.I.?

**Comment by ghDaYuYu** [comment] 2021-03-27 01:43
... I was expecting some glitches on the filtering as there are a few new lines of code in there.
Good catch!
Regards

**Comment by stephen147** [comment] 2021-03-27 15:26
> Are sources tagged (either with artist, artist Id, master Id or release Id) or untagged?

Yes, they were tagged previously. I have an album that contains a bonus track that I was trying to tag again which there's a bug for that here: https://github.com/ghDaYuYu/foo_discogs/issues/11

**Comment by ghDaYuYu** [comment] 2021-03-27 17:47
Unsure about a relation to the hidden tracks issue. Hopefully I will come across this issue at some point, for now I am unable to reproduce this bug here, sorry.

**Comment by stephen147** [comment] 2021-03-27 19:19
I was just referring to that the tags you mentioned were present.

**Comment by ghDaYuYu** [comment] 2021-03-27 20:00
Yep, I was thinking to myself if they were related : )
If you can provide further help to replicate that empty list,  I'll will try to debug it, otherwise it will show up sometime on some other use case.
Cheers

**Comment by stephen147** [comment] 2021-03-27 20:19
All I can say is this is the release that I was trying:

https://www.discogs.com/release/2707287

**Comment by ghDaYuYu** [comment] 2021-06-02 17:05
I’m closing this issue because it has been inactive for a few months.

Please reopen if you want to leave us a comment!

Thank you!

**Comment by stephen147** [comment] 2021-06-02 17:09
Still having this issue. I can't reopen this. Shall I start a new issue?

**Comment by ghDaYuYu** [comment] 2021-06-02 18:29
Reopening...

**Comment by ghDaYuYu** [comment] 2021-08-18 00:58
I am closing this issue as the Show Id feature is no longer available after the release is presented as a tree vs a list.
If that particular release still triggers a bug, please open a new issue.
Thanks for reporting!

**Closed by ghDaYuYu** 2021-08-18 00:58 UTC

**Comment by stephen147** [comment] 2021-08-18 11:44
All works great now. Thanks.
