### ISSUE TITLE
discogger crashes fb2k v2 x64 b10

### ISSUE THREAD

**Issue by Barough** [ghDaYuYu/foo_discogs#78] opened 2022-09-23 18:37 UTC
foobar crashes at start on and off.

crash log attached

[crash report.zip](https://github.com/ghDaYuYu/foo_discogs/files/9636375/crash.report.zip)

**Comment by ghuDaYuYu** [comment] 2022-09-23 20:16
thanks for the report...  looks like a crash calling GdiplusLoadIconEx, at a very early loading stage.
maybe downloading the component again from the repo may solve it, if you foo_discogger installation become corrupt somehow.

**Comment by Barough** [comment] 2022-09-23 23:35
i'll do that after i get some sleep and report back.

**Comment by Barough** [comment] 2022-09-24 09:27
No crashes so far after the re-installation of the component

**Comment by ghuDaYuYu** [comment] 2022-09-24 21:23
Nice one!
Just reopen the issue if you encounter the same problem again.

**Comment by Barough** [comment] 2022-10-06 12:45
Crashes on both Win 10 & 11 now
[crash.zip](https://github.com/ghDaYuYu/foo_discogs/files/9724908/crash.zip)

**Comment by ghuDaYuYu** [comment] 2022-10-07 08:55
Although it will take still some time to release 1.0.15, you can try this version instead if you'd like:

[zipped 1.0.14.6 prerelease](https://github.com/ghDaYuYu/foo_discogs/files/9693395/zip.1.0.14.6.prerelease.zip)

A few crashes were fixed since 1.0.14.0, although none related to loading resources (icons, etc) as in your reports, will check if I can find something wrong in there, will write back if a fix becomes available.

**Comment by Barough** [comment] 2022-10-07 12:02
Forgot to write this in my previous reply......
The latest crashes, happens just after the upgrade to the new Beta 11. No crashes after that.

**Comment by ghuDaYuYu** [comment] 2022-10-07 13:17
Can not reproduce ... did not crash after updating to beta 11 here.
Next Discogger release is including a full revision of issues related to file system code pages, not only importing and exporting tag mappings but the installation of the component itself. That might fix issues with users installing the component in unicode path locations.
But you reports seam to point to a problem loading resources. Should be checking that at some point... good news it is working again after the initial crashes!

**Comment by ghuDaYuYu** [comment] 2022-10-08 18:20
> The latest crashes, happens just after the upgrade to the new Beta 11. No crashes after that.

I gave it another try and made it crash. Not a complete solution, as there seems to be more bugs involved, but patch 9787bc1b covers a few crash scenarios during installation/updates.
Thanks for clarification...
I am reopening this issue, maybe just temporarily, until next release date.

**Comment by Barough** [comment] 2022-10-12 13:08
I have the latest Discogger installed ie. v1.0.14.7: rev 14.7 (3) but now after the updated to Beta 12 so does it crash again
[crash.zip](https://github.com/ghDaYuYu/foo_discogs/files/9765113/crash.zip)

**Comment by ghuDaYuYu** [comment] 2022-10-13 01:03
Sorry about the mangled release names at the download page, it has been corrected now to v1.0.14.7.
Also thanks a lot for providing more info.

> I have the latest Discogger installed ie. v1.0.14.7: rev 14.7 (3) but now after the updated to Beta 12 so does it crash again

I am a bit clueless, does reinstalling the component in you standard mode solve it?

In any case, here is [v1.0.14.8](https://github.com/ghDaYuYu/foo_discogs/releases/tag/v1.0.14.8).
Caption icon has been modded, it seems to have relation to your first and last crash reports, and the project resource locale is now set to neutral.

**Comment by Barough** [comment] 2022-10-13 02:51
Beats me whats going on neither. Crash on installed foobar but not on the portable.

As before, no crashes after the first start after the upgrade to B12.

**Comment by ghuDaYuYu** [comment] 2022-10-13 21:52
You may try the preview attached below, or maybe just leave it till next fb2k beta?
I reckon I've never run fb2k standard mode until now, all my tests were all performed on portable and, from time to time, linux portable. Nevertheless I had a go today, and tested for this particular issue :

- both 32 and 64 bits standard simultaneous installs and updates
- destination folder 'Program Files/ñ' and 'Program Files (x86)/ñ'.
- steps: installing beta 11 + install component (v1.0.14.9) + update to beta 12

But could not make it crash.

New fixes/revisions in 14.9:
- increased caption resource id to a number higher that fb2k id.
- preference panel tab changes confirmation dialog dark mode.

[zip v1.0.14.9](https://github.com/ghDaYuYu/foo_discogs/files/9780865/zip.1.0.14.9.zip)

**Comment by Barough** [comment] 2022-10-23 19:33
Just grabbed and installed 14.9. Waiting for a new foobar beta to show up.

**Comment by Barough** [comment] 2022-11-16 19:07
No crash this time after the upgrade to Beta 13 :)

**Comment by ghuDaYuYu** [comment] 2022-11-28 06:41
Thanks for your help fixing this issue!

I'd like to apologize in advance for the inconvenience as I am having doubts about this issue being 100% fixed.
Can we keep this issue open for a while, if you do not mind, and close it after some further non-crashing fb2k v2 update iterations?

note to self:
check global resource initialization execution context.

**Comment by Barough** [comment] 2022-11-28 07:01
Keep it open until your sure it's fully fixed

**Comment by ghuDaYuYu** [comment] 2022-11-30 21:23
Test report:
fb2k v2 Beta 14 update (standard and portable installation, over 64bits beta 13, foo_discogger v1.0.14.9) crash test has passed here.

**Comment by Barough** [comment] 2022-12-01 00:27
No crashes here after the b14 update

**Comment by ghuDaYuYu** [comment] 2022-12-01 08:47
Nice... then when I find some time to build and write the summary, v1.0.14.9pv will become release v1.0.15.

**Comment by Barough** [comment] 2022-12-02 05:36
No crash after the Beta 15 update

**Comment by Barough** [comment] 2022-12-27 03:59
Still working prefect after the Beta 19 update. :)

**Comment by ghuDaYuYu** [comment] 2023-01-04 11:13
Nice, I will soon also give Beta 20 a try, still need to find a moment of quiet to compile v.1.0.15 with all 14.x updates together with some additional fix/feature to further justify a new release.

**Comment by Barough** [comment] 2023-01-04 18:51
Beta 20 works fine also. :)

**Comment by Lichtenshtein** [comment] 2023-02-12 00:35
Not a crash, discogger just won't load, I guess?

![11-02-2023-234042-2](https://user-images.githubusercontent.com/13855295/218286899-09f86972-ff7e-4196-a16c-976809aee537.png)

It appears every time i start the player.

> Failed to load DLL: foo_discogger.dll  
> Reason: The specified procedure was not found.  

Reinstalling, upgrading, rolling back to an older version of the plugin does not help.

foobar2000 v2.0 beta 23 [x86]

After checking, the same error occurs with clean foobar2000 v1.6.16

I definitely used one of the old versions of discogger with foobar v2.x, I don't remember which one. But everything worked up to some point.

Does the plugin have any system requirements for the operating system? Could they have changed?

Windows 10 x64 1607.

**Comment by ghuDaYuYu** [comment] 2023-02-12 04:58
Hello [Lichtenshtein](https://github.com/Lichtenshtein),
I am creating a reference from a new issue if you don´t mind, as next v2 beta might be crashing again...
Thanks for reporting!

**Comment by ghuDaYuYu** [comment] 2023-02-12 05:29
Beta 24 still not crashing . . . 🔢

**Comment by Barough** [comment] 2023-02-26 09:53
No issues after upgrading to Beta 25.

Really think that this issue can be closed now.

**Comment by ghuDaYuYu** [comment] 2023-02-26 22:44
Yes, let close it... It is been a pleasure. I should resume testing in this issue.
My conclusion is that there where some jobs loading graphic resources at start up, maybe being called from the wrong context.
Will need to investigate a bit further on my own.
Its been a pleasure.... Best regards!

**Closed by ghuDaYuYu** 2023-02-26 22:44 UTC
